[package]
edition = "2021"
name = "tapo-exporter"
version = "0.1.0"

[dependencies]
metrics = "0.24.1"
metrics-exporter-prometheus = "0.16.2"
metrics-util = "0.19.0"
tapo = "0.8.0"
tokio = { version = "1", features = ["full"] }
