[package]
edition = "2021"
name = "tapo-exporter"
version = "0.1.0"

[dependencies]
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.0"
metrics-util = "0.19.1"
tapo = "0.8.1"
tokio = { version = "1", features = ["full"] }
