version: '3'

env:
  short_sha:
    sh: echo $(git rev-parse --short HEAD)

tasks:
  version:
    cmds:
      - echo {{.short_sha}}

  container-build:
    cmds:
      - docker build -t ghcr.io/sousandrei/tapo-exporter:{{.short_sha}} -f Containerfile .

  container-push:
    cmds:
      - docker push ghcr.io/sousandrei/tapo-exporter:{{.short_sha}}
